<?php

namespace App\Helpers;

use Illuminate\Support\Facades\Facade;

class BackupFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'backupclass';
    }

}
